apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  type: NodePort  # or LoadBalancer, depending on your access needs
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
